import type {
  DiceCombination,
  DiceCombinationKind,
  EnemyDefinition,
  EnemyId,
  HeroDefinition,
  HeroId,
  TalentDefinition,
  WaveDefinition,
} from "./types";

export const HEROES: Record<HeroId, HeroDefinition> = {
  knight: {
    id: "knight",
    name: "蒼鋼騎士",
    classLabel: "守護",
    color: "#3d82d8",
    icon: "K",
    range: 0.2,
    attack: 7,
    maxHp: 112,
    attackInterval: 1.05,
    role: "tank",
    tierNotes: { 1: "阻擋 1 名敵人", 2: "阻擋 2 名，帶擊退", 3: "阻擋 3 名，定期護盾" },
  },
  fireMage: {
    id: "fireMage",
    name: "燼焰法師",
    classLabel: "火術",
    color: "#e76450",
    icon: "F",
    range: 0.62,
    attack: 16,
    maxHp: 56,
    attackInterval: 1.35,
    role: "area",
    tierNotes: { 1: "火球單體", 2: "命中小範圍爆炸", 3: "三目標燃燒" },
  },
  archer: {
    id: "archer",
    name: "翠羽弓手",
    classLabel: "疾射",
    color: "#40a56f",
    icon: "A",
    range: 0.78,
    attack: 11,
    maxHp: 62,
    attackInterval: 0.64,
    role: "single",
    tierNotes: { 1: "快速單箭", 2: "第四箭穿透", 3: "連射與暴擊" },
  },
  priest: {
    id: "priest",
    name: "晨曦祭司",
    classLabel: "祈禱",
    color: "#a877c7",
    icon: "P",
    range: 0.56,
    attack: 5,
    maxHp: 72,
    attackInterval: 1.25,
    role: "support",
    tierNotes: { 1: "治療最虛弱者", 2: "治療 2 名", 3: "治療並加速" },
  },
  ranger: {
    id: "ranger", name: "森林遊俠", classLabel: "狙擊", color: "#4f9a64", icon: "R", range: 0.88, attack: 14, maxHp: 58, attackInterval: 0.72, role: "single",
    tierNotes: { 1: "遠距狙擊", 2: "箭矢穿透", 3: "連環獵射" },
  },
  engineer: {
    id: "engineer", name: "機關技師", classLabel: "工坊", color: "#c7803f", icon: "E", range: 0.66, attack: 10, maxHp: 74, attackInterval: 1.08, role: "area",
    tierNotes: { 1: "部署齒輪彈", 2: "小範圍連鎖", 3: "過載砲塔" },
  },
  deathKnight: {
    id: "deathKnight", name: "死亡騎士", classLabel: "冥衛", color: "#6d5da3", icon: "D", range: 0.28, attack: 12, maxHp: 128, attackInterval: 1.15, role: "tank",
    tierNotes: { 1: "阻擋 1 名敵人", 2: "吸收傷害", 3: "冥火護幕" },
  },
  bard: {
    id: "bard", name: "水樂吟遊詩人", classLabel: "和鳴", color: "#48aab8", icon: "B", range: 0.58, attack: 6, maxHp: 68, attackInterval: 1.02, role: "support",
    tierNotes: { 1: "治療最虛弱者", 2: "治療並加速", 3: "全隊和鳴" },
  },
  fighter: {
    id: "fighter", name: "武鬥家", classLabel: "格鬥", color: "#c85a43", icon: "F", range: 0.34, attack: 17, maxHp: 92, attackInterval: 0.84, role: "single",
    tierNotes: { 1: "近戰連擊", 2: "重拳追擊", 3: "暴烈旋風" },
  },
  frostQueen: {
    id: "frostQueen", name: "冰霜女王", classLabel: "霜術", color: "#5d91d5", icon: "Q", range: 0.76, attack: 14, maxHp: 61, attackInterval: 1.3, role: "area",
    tierNotes: { 1: "冰晶單體", 2: "寒霜擴散", 3: "凍結風暴" },
  },
  assassin: {
    id: "assassin", name: "暗影刺客", classLabel: "瞬擊", color: "#85529d", icon: "S", range: 0.67, attack: 21, maxHp: 50, attackInterval: 0.9, role: "single",
    tierNotes: { 1: "伏擊最前敵人", 2: "影步追斬", 3: "雙刃處決" },
  },
};

export const ENEMIES: Record<EnemyId, EnemyDefinition> = {
  slime: { id: "slime", name: "藍史萊姆", color: "#55a5dd", hp: 34, speed: 0.04, attack: 7, attackInterval: 1.2, castleDamage: 1, tags: [] },
  wolf: { id: "wolf", name: "疾風狼", color: "#c49255", hp: 25, speed: 0.077, attack: 6, attackInterval: 0.85, castleDamage: 1, tags: [] },
  shieldSoldier: { id: "shieldSoldier", name: "盾牌兵", color: "#76869a", hp: 78, speed: 0.032, attack: 9, attackInterval: 1.3, castleDamage: 2, tags: ["shield"] },
  goblinArcher: { id: "goblinArcher", name: "哥布林弓手", color: "#a27a4d", hp: 45, speed: 0.038, attack: 8, attackInterval: 1.1, castleDamage: 1, range: 0.46, tags: ["ranged"] },
  shaman: { id: "shaman", name: "苔角薩滿", color: "#789f68", hp: 55, speed: 0.03, attack: 5, attackInterval: 1.4, castleDamage: 1, tags: ["healer"] },
  bomber: { id: "bomber", name: "爆彈怪", color: "#d8794f", hp: 42, speed: 0.052, attack: 10, attackInterval: 1.1, castleDamage: 2, tags: ["bomber"] },
  eliteGiant: { id: "eliteGiant", name: "苔岩巨人", color: "#66835f", hp: 320, speed: 0.022, attack: 15, attackInterval: 1.45, castleDamage: 4, tags: ["elite"] },
  boss: { id: "boss", name: "碎骰巨靈", color: "#5c4b9d", hp: 720, speed: 0.018, attack: 19, attackInterval: 1.3, castleDamage: 6, tags: ["boss", "elite"] },
};

export const DICE_COMBINATIONS: Record<DiceCombinationKind, DiceCombination> = {
  NONE: { kind: "NONE", label: "無組合", priority: 0, description: "獲得 1 點召喚能量" },
  PAIR: { kind: "PAIR", label: "一對", priority: 1, description: "隨機召喚 1 名 T1 英雄" },
  TWO_PAIR: { kind: "TWO_PAIR", label: "兩對", priority: 2, description: "隨機召喚 2 名 T1 英雄" },
  THREE_KIND: { kind: "THREE_KIND", label: "三條", priority: 3, description: "選擇 1 種英雄召喚" },
  SMALL_STRAIGHT: { kind: "SMALL_STRAIGHT", label: "小順子", priority: 4, description: "本波全體攻速 +20%" },
  LARGE_STRAIGHT: { kind: "LARGE_STRAIGHT", label: "大順子", priority: 5, description: "本波攻擊 +25%、攻速 +15%" },
  FULL_HOUSE: { kind: "FULL_HOUSE", label: "葫蘆", priority: 6, description: "免費升階 1 名可升級英雄" },
  FOUR_KIND: { kind: "FOUR_KIND", label: "四條", priority: 7, description: "發動隊長技能" },
  FIVE_KIND: { kind: "FIVE_KIND", label: "五條", priority: 8, description: "發動全畫面必殺技" },
};

export const TALENTS: TalentDefinition[] = [
  { id: "reroll-plus", name: "靈巧指節", description: "重骰次數 +1。", rarity: "common", maxStacks: 2, effect: "extra-reroll" },
  { id: "free-reroll", name: "第一次免費", description: "每波第一次重骰不消耗次數。", rarity: "rare", maxStacks: 1, effect: "free-first-reroll" },
  { id: "six-power", name: "六面加護", description: "每顆 6 使全隊攻擊 +5%。", rarity: "rare", maxStacks: 3, effect: "six-power" },
  { id: "pair-safety", name: "幸運保底", description: "無組合保底提前 1 回合。", rarity: "common", maxStacks: 1, effect: "pair-safety" },
  { id: "straight-call", name: "行軍節拍", description: "小順子額外召喚 1 名英雄。", rarity: "rare", maxStacks: 1, effect: "small-straight-summon" },
  { id: "pair-echo", name: "成對回響", description: "一對有 20% 機率多召喚 1 名。", rarity: "common", maxStacks: 2, effect: "pair-extra-summon" },
  { id: "merge-burst", name: "升階衝擊", description: "合成 T2 時對全場造成 36 傷害。", rarity: "rare", maxStacks: 2, effect: "merge-damage" },
  { id: "third-act", name: "終幕呼喚", description: "合成 T3 時隨機召喚 1 名 T1。", rarity: "epic", maxStacks: 1, effect: "t3-summon" },
  { id: "merge-shield", name: "聚光護幕", description: "合成後英雄獲得 22 護盾。", rarity: "common", maxStacks: 3, effect: "merge-shield" },
  { id: "quick-start", name: "首演捷徑", description: "本局第一次合成只需 2 名。", rarity: "epic", maxStacks: 1, effect: "two-merge" },
  { id: "t1-tempo", name: "新兵節奏", description: "T1 英雄攻速 +15%。", rarity: "common", maxStacks: 2, effect: "t1-speed" },
  { id: "t3-force", name: "金冠決意", description: "T3 英雄攻擊 +30%。", rarity: "rare", maxStacks: 2, effect: "t3-attack" },
  { id: "firecraft", name: "餘燼工坊", description: "火焰傷害 +25%。", rarity: "common", maxStacks: 3, effect: "fire-damage" },
  { id: "shield-wall", name: "鋼鐵陣列", description: "騎士阻擋數 +1。", rarity: "rare", maxStacks: 2, effect: "knight-block" },
  { id: "eagle-eye", name: "翠羽瞄準", description: "弓手暴擊率 +15%。", rarity: "common", maxStacks: 2, effect: "archer-crit" },
  { id: "morning-light", name: "曙光祈願", description: "祭司治療量 +30%。", rarity: "common", maxStacks: 3, effect: "priest-heal" },
  { id: "triad", name: "三色合鳴", description: "隊伍有 3 種職業時，全隊攻擊 +15%。", rarity: "epic", maxStacks: 1, effect: "three-job-attack" },
  { id: "neighbor-chorus", name: "相鄰合奏", description: "同職相鄰時，各自攻速 +10%。", rarity: "rare", maxStacks: 3, effect: "neighbor-speed" },
];

export const WAVES: WaveDefinition[] = [
  { wave: 1, title: "初幕：小小來客", enemies: [{ enemyId: "slime", count: 5 }], rewardTalent: false },
  { wave: 2, title: "疾步穿行", enemies: [{ enemyId: "slime", count: 4 }, { enemyId: "wolf", count: 3 }], rewardTalent: false },
  { wave: 3, title: "林間騷動", enemies: [{ enemyId: "slime", count: 5 }, { enemyId: "wolf", count: 4 }], rewardTalent: true },
  { wave: 4, title: "精英：苔岩巨人", enemies: [{ enemyId: "eliteGiant", count: 1 }, { enemyId: "shieldSoldier", count: 3 }], rewardTalent: false },
  { wave: 5, title: "盾陣推進", enemies: [{ enemyId: "shieldSoldier", count: 4 }, { enemyId: "goblinArcher", count: 3 }], rewardTalent: false },
  { wave: 6, title: "灼熱行軍", enemies: [{ enemyId: "bomber", count: 4 }, { enemyId: "shaman", count: 2 }, { enemyId: "wolf", count: 4 }], rewardTalent: true },
  { wave: 7, title: "長路混戰", enemies: [{ enemyId: "slime", count: 5 }, { enemyId: "goblinArcher", count: 4 }, { enemyId: "shieldSoldier", count: 3 }], rewardTalent: false },
  { wave: 8, title: "破陣的火花", enemies: [{ enemyId: "bomber", count: 5 }, { enemyId: "wolf", count: 5 }, { enemyId: "shaman", count: 2 }], rewardTalent: false },
  { wave: 9, title: "精英：巨人再臨", enemies: [{ enemyId: "eliteGiant", count: 1 }, { enemyId: "goblinArcher", count: 4 }, { enemyId: "shieldSoldier", count: 4 }], rewardTalent: true },
  { wave: 10, title: "終幕：碎骰巨靈", enemies: [{ enemyId: "boss", count: 1 }, { enemyId: "wolf", count: 4 }, { enemyId: "bomber", count: 3 }], rewardTalent: false },
];
